%macro get_nearby_genes_by_dist(
gtf,/*GTF sas data set generated by the macro get_genecode_gtf_data*/
dist=5e4,
outputdsd=combined_genes_by_dist,
output_cnts4genes=gene_cnts,
max_gene_cnts4histgram=100
);
data gtf_hg38;
set &gtf;
run;
data gtf_hg38;
set gtf_hg38;
where type="gene";
keep genesymbol chr st end;
run;

proc sql;
create table &outputdsd as
select a.*,b.genesymbol as nearby_genes,b.st as nearby_gst,b.end as nearby_gend
from gtf_hg38 as a
left join
gtf_hg38 as b
on a.chr=b.chr and (
(b.st between a.st-&dist and a.end+&dist) or
(b.end between a.st-&dist and a.end+&dist)
)
order by a.genesymbol;

proc freq data=&outputdsd noprint;
table genesymbol/list out=&output_cnts4genes;
run;

proc univariate data=&output_cnts4genes;
where count<&max_gene_cnts4histgram;
var count;
histogram count/vscale=count midpoints=1 to &max_gene_cnts4histgram by 2;
run;

%mend;

/*Demo codes:;

libname G "E:\LongCOVID_HGI_GWAS";

%get_nearby_genes_by_dist(
gtf=G.gtf_hg38,
dist=1e4,
outputdsd=combined_genes_by_dist,
output_cnts4genes=gene_cnts,
max_gene_cnts4histgram=100
);

*/

