%macro local_multigwas_manhattan(
GWAS_SAS_DSD=,
Marker_Col_Name=,
Marker_Pos_Col_Name=,
Xaxis_Col_Name=,
Yaxis_Col_Names=, /*Support multiple p-val vars*/
GWAS_dsdout=,
gwas_thrsd=, /*-log10(P) threshold, such as 5*/
Mb_SNPs_Nearby=,/*this Mb_factor will multiple 1,000,000 when running in the program*/
snps=,
design_width=1000,
design_height=200,
Labels4gwas_grps=,/*Supply labels for the Yaxis_Col_Names in the final lattice plot, 
ensuring the same order and no blank spaces are allowed!*/
);

%let N_gwas=%ntokens(&Yaxis_Col_Names);
%do gwas_i=1 %to &N_gwas;
   %let Marker_Col_Name=%assign_str4missing(Inval=&Marker_Col_Name,NewVal=SNP);
   %let Xaxis_Col_Name=%assign_str4missing(Inval=&Xaxis_Col_Name,NewVal=Chr);
   %let Yaxis_Col_Name=%scan(&Yaxis_Col_Names,&gwas_i,%str( ));
   %let Marker_Pos_Col_Name=%assign_str4missing(Inval=&Marker_Pos_Col_Name,NewVal=BP);
   %let gwas_label=%qscan(&Labels4gwas_grps,&gwas_i,%str( ));
   
   /*Create numeric rank for these snps based on its order and use it to order them in the final plot*/
    %rank4grps(
     grps=&snps,
     dsdout=snp_rank
     );
     
     *apply format to sort panel by a;
    %mkfmt4grps_by_var(
    grpdsd=snp_rank,
    grp_var=grps,
    by_var=num_grps,
    outfmt4numgrps=grps2nums,
    outfmt4chargrps=nums2grps
    );
   
/*      
   %char2num_dsd(dsdin=&GWAS,
                 vars=&Yaxis_Col_Name &Marker_Pos_Col_Name,
                 dsdout=&GWAS_dsdout);
*/               
   %put Now we are going to keep SNPs &Mb_SNPs_Nearby Mb up/downstream of GWS hits;
   data tops;
   set &GWAS_SAS_DSD;
   *Add a group column and center position column;
   *Note: here we use scaled pos, which it at the center of a window with 1000 bp;
   center_pos=500;
   grp=&Marker_Col_Name;
   where &Marker_Col_Name in (%quotelst(&snps));
   run;
   /*make snp grp for ordering it in the final manhanttan plot*/
   
   
   *Merge these top signals and only keep the most significant signals around specific dist;
   %get_top_signal_within_dist(dsdin=tops
                           ,grp_var=&Xaxis_Col_Name
                           ,signal_var=&Yaxis_Col_Name
                           ,pos_var=&Marker_Pos_Col_Name
                           ,pos_dist_thrshd=&Mb_SNPs_Nearby*1
                           ,dsdout=tops);
                           
*No need to merge the above top signals, as we will put the query snps at the center of each window;
*To keep the script simple, we just make the pos_dist_threhd as 1=&Mb_SNPs_Nearby*1, which will not;
*merge these signals;
                         
   proc sql;
   create table &GWAS_dsdout(where=(tmp^="")) as
   select a.*,b.&Marker_Col_Name as tmp,b.grp,b.center_pos,
          catx(':',b.&Xaxis_Col_Name,b.grp) as new_chr_tag
   from &GWAS_SAS_DSD as a
   right join
   tops as b
   on    a.&Xaxis_Col_Name=b.&Xaxis_Col_Name and 
         a.&Marker_Pos_Col_Name between 
         (b.&Marker_Pos_Col_Name-&Mb_SNPs_Nearby*1000000*0.5) and (b.&Marker_Pos_Col_Name+&Mb_SNPs_Nearby*1000000*0.5)
   order by a.&Xaxis_Col_Name,
         a.&Marker_Pos_Col_Name;
         
/*    data &GWAS_dsdout; */
/*    set &GWAS_dsdout; */
/*    drop tmp; */
/*    run;                  */
   *Remove duplicates generated by the above codes;
   proc sort data=&GWAS_dsdout nodupkeys;by _all_;run;
   proc sort data=&GWAS_dsdout;by &Xaxis_Col_Name &Marker_Pos_Col_Name;run;
   *Make manhattan plots for regions with top hits;
   *It is necessary to use new chr group for the xaxis label;
   *%manhattan(dsdin=&GWAS_dsdout,pos_var=&Marker_Pos_Col_Name,chr_var=new_chr_tag,P_var=&Yaxis_Col_Name,logP=1,gwas_thrsd=&gwas_thrsd);

   *Use proc sgpanel to make local manhattan plots, which are better;
   *The factor4mult will make the axis start from 0 to 1000;
    %scale4range(
      dsdin=&GWAS_dsdout,
      ids=new_chr_tag,
      vars=&Marker_Pos_Col_Name,
      factor4mult=1000,
      round_or_not=1,
      outdsd=&GWAS_dsdout
      );
     data &GWAS_dsdout;
     set &GWAS_dsdout;
     logP=-log10(&Yaxis_Col_Name);
     label logP='-log10(P)';
     run;
     data &GWAS_dsdout;
     set &GWAS_dsdout;
     top_tag=0;
/*      this will interupted with center_pos */
/*      if logP>=&gwas_thrsd then top_tag=1; */
     if trim(left(scan(new_chr_tag,-1,':')))=&Marker_Col_Name then top_tag=2;
     *Only keep center positon when the marker is the center snp;
     if trim(left(scan(new_chr_tag,-1,':')))^=&Marker_Col_Name then center_pos=.;

     *Get the x position for the query SNP;
     *As there would be multiple query SNPs, use mean of x positions;
     *This is not good and replaced by the center position 500;
     proc sql noprint;
     select ceil(mean(&Marker_Pos_Col_Name)) into: xpos4topsnp 
     from &GWAS_dsdout
     where &Marker_Col_Name in (%quotelst(&snps));

     *Get the x position for top signal for making refline;
/*     proc sql noprint;
     select &Marker_Pos_Col_Name into: xpos4topsnp
     from &GWAS_dsdout
     having logP=max(logP);
*/
     
/*
     proc sort data=&GWAS_dsdout;by tmp logP;
     data &GWAS_dsdout;
     set &GWAS_dsdout;
     if last.tmp then do;
        top_tag=2;
     end;
     by tmp;
*/
     
     *Add snp rank into the dataset for ordering the subplots;
     proc sql;
     create table &GWAS_dsdout._&gwas_i as
     select * 
     from &GWAS_dsdout as a
     left join
     snp_rank as b
     on a.tmp=b.grps;  
     *Add gwas p-value varname into the dataset;
     data &GWAS_dsdout._&gwas_i;
     *Important to set enough length for the var gwas;
     *otherwise, it will be truncated;
     %if %length(&Labels4gwas_grps)>0 %then %do;
       length gwas $%length(%sysfunc(compress(&Labels4gwas_grps)));
     %end;
     %else %do;
       length gwas $%length(%sysfunc(compress(&Yaxis_Col_Names)));
     %end;
     
     set &GWAS_dsdout._&gwas_i;
     gwas="&Yaxis_Col_Name";
     %if %length(&gwas_label)>0 %then %do;
       gwas="&gwas_label";
     %end;
     run;
%end;

*apply format to sort rowwide panel by a;
%if %length(&Labels4gwas_grps)>0 %then %let gwas_info=&Labels4gwas_grps;
%else %let gwas_info=&Yaxis_Col_Names;
%rank4grps(
     grps=&gwas_info,
     dsdout=gwas_rank
);
*make order for the var gwas based on user input order;   
%mkfmt4grps_by_var(
    grpdsd=gwas_rank,
    grp_var=grps,
    by_var=num_grps,
    outfmt4numgrps=gwas_grps2nums,
    outfmt4chargrps=nums2gwas_grps
);

*combine all gwas sub data sets;
data &gwas_dsdout;
set %do xgwas=1 %to &N_gwas;
     &GWAS_dsdout._&xgwas
%end;
;
new_num_grps=input(grps,grps2nums.);
new_num_gwas_grps=input(gwas,gwas_grps2nums.);
run;    

*Need to further adjust pos based on its difference with the center pos = 500;
data _null_;
set &GWAS_dsdout(where=(top_tag=2));
call symputx('diff_dist',500-pos);
run;
data &GWAS_dsdout;
set &GWAS_dsdout;
pos=pos+&diff_dist;
run;

    *Make a panel of plots with the same xaxis;
    *https://documentation.sas.com/doc/en/pgmsascdc/9.4_3.5/grstatproc/p1dt33l6a6epk6n1chtynsgsjgit.htm;
    *https://documentation.sas.com/doc/en/pgmsascdc/9.4_3.5/grstatproc/p0qva1ws6twy5xn0zdl3nslyynvp.htm;
    *https://blogs.sas.com/content/iml/2018/06/13/attrpriority-cycleattrs-styleattrs-ods-graphics.html;
    title "Scatterplots for &snps";
    ods graphics /reset=all height=&design_height.px width=&design_width.px
    antialiasmax=50000000 attrpriority=none;
/*     Need to make attrpriority as none to use the combination of color and symbol */
     proc sgpanel data=&GWAS_dsdout noautolegend;
/*   panelby num_grps/layout=columnlattice onepanel novarname noheader; */
*Remove header, as the order of subplots are according to the input snp order;
     format new_num_grps nums2grps. new_num_gwas_grps nums2gwas_grps.;
     panelby new_num_grps new_num_gwas_grps/layout=lattice onepanel novarname;
     styleattrs datacolors=(darkred darkorange darkblue) 
     datacontrastcolors=(lightblue darkred SteelBlue)
     datasymbols=(circlefilled diamondfilled circlefilled);
     refline &gwas_thrsd/axis=y lineattrs=(color=darkred pattern=thindot);
     *add the -log10(0.05) refline for the yaxis;
     refline 1.29/axis=y lineattrs=(color=darkred pattern=thindot);
/*      refline &xpos4topsnp/axis=x lineattrs=(color=darkgreen pattern=dot thickness=2);      */
     refline 500/axis=x lineattrs=(color=darkgreen pattern=dot thickness=2);   
/*      Note: datasymbols option will be overwritten by markerattrs option symbol; */
/*      scatter x=&Marker_Pos_Col_Name y=logP/group=top_tag markerattrs=(symbol=circlefilled size=6) name="sc"; */
     scatter x=&Marker_Pos_Col_Name y=logP/group=top_tag markerattrs=(size=10) name="sc";
     *Also add the label for the center snp;
     scatter x=center_pos y=logP/markerattrs=(size=15 symbol=diamondfilled color=lightred) name="center_snp";     
     rowaxis display=all label='-log10(association P)';
     colaxis display=(noticks novalues nolabel);
     run;   

%mend;

/*Demo:

*options mprint mlogic symbolgen;
%let macrodir=/home/cheng.zhong.shan/Macros;
%include "&macrodir/importallmacros_ue.sas";
%importallmacros_ue;

libname FM '/home/cheng.zhong.shan/my_shared_file_links/cheng.zhong.shan/F_vs_M_Covid19_Hosp';
*options mprint mlogic symbolgen;

%local_multigwas_manhattan(
GWAS_SAS_DSD=FM.f_vs_m_mixedpop,
Marker_Col_Name=rsid,
Marker_Pos_Col_Name=pos,
Xaxis_Col_Name=chr,
Yaxis_Col_Names=pval gwas1_p gwas2_p,
GWAS_dsdout=xxx,
gwas_thrsd=5.5,
Mb_SNPs_Nearby=1,
snps=rs16831827 rs2564978 rs12474050,
design_width=1600,
design_height=1200,
Labels4gwas_grps=
);
*Need to add quit to only show one figure;
quit;

*/
