%macro make_heart_pict(
heart_color=pink,
non_heart_area_color=lightgreen,
pict_width_inch=10,
pict_height_inch=10
);
*If want to draw a circle, just replace x and y with x=sin(t) and y=cost(t);
*if want to draw a beet-like shape, just use x=sin(t)**3 and y=cos(t);
data heart;
     pi = constant('PI');
     do deg = 0 to 360 by 1;
          t = deg * pi / 180;
          x = 16 * sin(t)**3;
          y = 13 * cos(t) - 5 * cos(2*t) - 2 * cos(3*t) - cos(4*t);
          id = 1;
          output;
     end;
run;
*Remove the last value to prevent from drawing a line in the middle of the heart;
data heart;
set heart end=eof;
if eof then do;
output;
x=0;y1=-17;y=.;output;
x=0;y1=-20; y=.;output;
end;
else do;
output;
end;
run;

/*%let heart_color=pink;*/
/*%let non_heart_area_color=lightgreen;*/
goptions cback=&non_heart_area_color
hsize=&pict_height_inch.in vsize=&pict_width_inch.in;
symbol1 v=none i=join c=black;

*This is for drawing a vertical line to cover the pink line generated by the plot1 statement;
symbol2 v=empty i=join c=&non_heart_area_color;

pattern1 v=solid c=&heart_color; /*Used to fill the inside of heart, corresponding to the lower area 1*/
*If pattern2 is not provided, the default value for pattern2 would be: v=solid c=white;
*this is corresponding to the upper area 2 for the statement "area=2";
pattern2 v=empty c=&non_heart_area_color;
/*Used to make the middle of the heart as transparent and the color white acutally does not affect anything!*/
*The above v=empty is important to have pink color in the middle of the heart;

*Or just make it as solid and color it with pink;
/*pattern2 v=solid c=&heart_color;*/

axis1 v=none label=none minor=none major=none c=&non_heart_area_color;
/*axis2  order=(-20 to 20);*/
/*axis3  order=(-20 to 20);*/
*It is important to fix the two yaxes with the same range;
axis2 v=none label=none minor=none major=none c=&non_heart_area_color order=(-20 to 20);
axis3 v=none label=none minor=none major=none c=&non_heart_area_color order=(-20 to 20);
*v=none label=none minor=none major=none c=white;
proc gplot data=heart;
/*plot y*x/area=2 haxis=axis1 vaxis=axis2 noframe;*/
plot1 y*x/area=2 vaxis=axis2 haxis=axis1 noframe skipmiss;
*Without the following statement, there would be needle for the heart;
*draw a white line to cover it;
plot2 y1*x/vaxis=axis3;
run;
%mend;
/*Demo codes:;

%make_heart_pict(
heart_color=blue,
non_heart_area_color=green,
pict_width_inch=5,
pict_height_inch=5
);

%make_heart_pict(
heart_color=pink,
non_heart_area_color=white,
pict_width_inch=5,
pict_height_inch=5
);

%make_heart_pict(
heart_color=white,
non_heart_area_color=lightred,
pict_width_inch=5,
pict_height_inch=5
);

*/

