%macro OpenSVG_Printer(
filename=mysvgfilename,
svgfileref=out,
other_paras4ods_graphics=%str(reset=all height=800 width=400 noborder)
);
options printerpath=(svg &svgfileref) nobyline;
filename out "&filename..svg";
ods listing close;
ods printer;
ods graphics on/outputfmt=svg
&other_paras4ods_graphics;

%mend;

/*Demo:
%OpenSVG_Printer(
filename=my_svg,
svgfileref=out,
other_paras4ods_graphics=%str(reset=all height=800 width=400 noborder)
);
*Put your codes here to generate plots;
ods printer close;
*Also need to close the fileref out generated by the macro;
filename out clear;
ods listing;
*/
