%macro scASE_betabino(
dsdin=x2,
model_var=x ,	 /*Currently it only accept one factor for the model statement*/
subj_var=subj,
read_var=A_cnt,
tot_var=tot
outdsd=nlmParameterEstimates
);

ods exclude all; 
*First estimate model parameters using proc fmm with betabinomial model;
/*ods trace on;*/
ods output ParameterEstimates=Fmm_ParameterEstimates;
proc fmm data=&dsdin;
*Do not treat x as categorical variable, as it will be different from the results generated by proc nlmixed;
*which treat x as numerical variable, and the first group '0' will be used as reference group;
/*class x;*/
model &read_var/&tot_var=&model_vars  /dist=betabinomial ;
run;
/*ods trace off;*/
ods exclude none;

proc sql noprint;
select Estimate into: b1_fmm_val 
from Fmm_ParameterEstimates
where Effect in ("&modelvars");
select Estimate into: b0_fmm_val 
from Fmm_ParameterEstimates
where Effect="Intercept";

/*ods trace on;*/
/*ods exclude all;*/
ods output ParameterEstimates=nlmParameterEstimates;
proc nlmixed data=&dsdin  QFAC=1 UPDATE=BFGS qmax=50 tech=QUANEW;
parm b0 &b0_fmm_val b1 &b1_fmm_val  a0 0.5 s2g 0.1;
linr=a0;
rho=1/(1+exp(-linr));
phi=(1-(rho**2))/(rho**2);
eta=b0+b1*x + u;
p=1/(1+exp(-eta));
n=&tot_var;
y=&read_var;
loglike=lgamma(n+1) - lgamma(y+1) - lgamma(n-y+1)+lgamma(phi)-
lgamma(n+phi)+lgamma(y+(phi*p)) +
lgamma((n-y)+phi*(1-p)) - lgamma(phi*p) - lgamma(phi*(1-p));
model y~general(loglike);
random u ~ normal(0,s2g) subject=&subj_var;
predict p out=prob_vals;
run;
/*ods trace off;*/
/*ods exclude none;*/

%mend;
