%macro umap_with_axes_restriction(
dsdin=new__tgt_dsd_,/*will generated by the macro sc_scatter4gene*/
umap_width=800,
umap_height=400,
lattice_or_not=0,
raxis_max=20000,
raxis_min=0,
caxis_max=,
caxis_min=45000);
ods graphics on/reset=all width=&umap_width height=&umap_height noborder;
proc sgpanel data=new__tgt_dsd_;
 *Only after using up the combination of all colors with the 1st datasymbol, it will use the combinations of;
 *colors with 2nd datasymbols, and the same applied to other datasymbols;
/*  styleattrs datacontrastcolors=(green gold red black blue grey pink)   */
/*             datasymbols=(circlefilled starfilled triangle diamond square circle) ; */

*Make all datapoints with the same symbol;
 styleattrs datacontrastcolors=(green gold red black blue grey pink)  
            datasymbols=(circlefilled) ;
*where &cell_type_var
 contains 'Ciliated';
panelby new_sgrp 
%if %eval(&lattice_or_not=1) %then %do;
                 &grpvar4boxplot /layout=lattice novarname noheader;
                 %end;
                 %else %do;
                 /onepanel rows=1 novarname noheader;
                 %end;
scatter x=x y=y /group=cluster
colorresponse=exp 
                 colormodel=(lightgray gold red) ;
*restrict x and y axis;                 
rowaxis 
%if &raxis_max ne %then %do;
max=&raxis_max
%end;
%if &raxis_min ne %then %do;
min=&raxis_min
%end;
;
  
colaxis 
%if &caxis_max ne %then %do;
max=&caxis_max
%end;
%if &caxis_min ne %then %do;
min=&caxis_min
%end;
;            
run;
%mend;

/*Demo code:
*Make sure use data data set new__tgt_dsd_ generated by the macro sc_scatter4gene;

%umap_with_axes_restriction(
dsdin=new__tgt_dsd_,
umap_width=800,
umap_height=300,
lattice_or_not=0,
raxis_max=20000,
raxis_min=0,
caxis_max=,
caxis_min=45000);

*/


